/* 1. Implement the Cinema database and create the database in SQL server. Don't forget to implement the primary and foreign keys. */

GO
CREATE DATABASE Cinema;

GO
USE Cinema;

GO
CREATE TABLE Rating
(
	RatingID INT IDENTITY(1,1) PRIMARY KEY,
	RatingName NVARCHAR(50) NOT NULL,
	RatingDescription NVARCHAR(255) NOT NULL
);

CREATE TABLE Movie 
(
	MovieID INT IDENTITY(1,1) PRIMARY KEY,
	Title NVARCHAR(50) NOT NULL,
	ReleaseDate DATE NOT NULL,
	Runtime INT NOT NULL,
	RatingID INT NOT NULL FOREIGN KEY REFERENCES Rating(RatingID),
);

CREATE TABLE Genre
(
	GenreID INT IDENTITY(1,1) PRIMARY KEY,
	GenreName NVARCHAR(50) NOT NULL
);

CREATE TABLE MovieGenre
(
	MovieGenreID INT IDENTITY(1,1) PRIMARY KEY,
	MovieID INT NOT NULL FOREIGN KEY REFERENCES Movie(MovieID),
	GenreID INT NOT NULL FOREIGN KEY REFERENCES Genre(GenreID)
);

CREATE TABLE Auditorium
(
	AuditoriumID INT IDENTITY(1,1) PRIMARY KEY,
	AuditoriumName NVARCHAR(50) NOT NULL,
	Available_Seats INT NOT NULL
);

CREATE TABLE Showing
(
	ShowingID INT IDENTITY(1,1) PRIMARY KEY,
	MovieID INT NOT NULL FOREIGN KEY REFERENCES Movie(MovieID),
	AuditoriumID INT NOT NULL FOREIGN KEY REFERENCES Auditorium(AuditoriumID),
	[Date] DATE NOT NULL,
	[Time] TIME NOT NULL
);

CREATE TABLE Customer
(
	CustomerID INT IDENTITY(1,1) PRIMARY KEY,
	FirstName NVARCHAR(100) NOT NULL,
	LastName NVARCHAR(100) NOT NULL,
	Gender CHAR NOT NULL,
	DOB DATE NOT NULL,
	Email NVARCHAR(255) NOT NULL,
	CHECK (Gender IN ('M','F'))
);

CREATE TABLE [Order]
(
	OrderID INT IDENTITY(1,1) PRIMARY KEY,
	CustomerID INT NOT NULL FOREIGN KEY REFERENCES Customer(CustomerID),
	OrderDate DATE NOT NULL
);

CREATE TABLE Category
(
	CategoryID INT IDENTITY(1,1) PRIMARY KEY,
	Name NVARCHAR(50) NOT NULL,
	[Description] NVARCHAR(255) NOT NULL
);

CREATE TABLE Ticket
(
	TicketID INT IDENTITY(1,1) PRIMARY KEY,
	ShowingID INT NOT NULL FOREIGN KEY REFERENCES Showing(ShowingID),
	CategoryID INT NOT NULL FOREIGN KEY REFERENCES Category(CategoryID),
	Price MONEY
);

CREATE TABLE OrderDetail
(
	OrderID INT FOREIGN KEY REFERENCES [Order](OrderID),
	TicketID INT FOREIGN KEY REFERENCES Ticket(TicketID),
	PRIMARY KEY (OrderID, TicketID)
);